---

language: 'python'
python: '2.7'

script:
  - echo localhost > inventory
  - ansible-playbook -i inventory test.yml --syntax-check
  - ansible-playbook -i inventory test.yml --connection=local --become
  - monit -V

env:
  global:
    - PPA: ppa:ansible/ansible-2.6
  matrix:
    - PPA: ppa:ansible/ansible-2.5

matrix:
  include:
    - os: linux
      sudo: required
      dist: precise
      install:
        - sudo add-apt-repository $FOO -y
        - sudo apt-get update -q
        - sudo apt-get install ansible
        - ansible --version
  exclude:
    - os: linux
      sudo: required
      dist: trusty
      before_install:
        - sudo add-apt-repository ppa:ansible/ansible-2.6 -y
        - sudo apt-get update -q
      install: 
        - sudo apt-get install ansible
        - ansible --version
    - os: linux
      sudo: required
      dist: xenial
      before_install:
        - sudo add-apt-repository ppa:ansible/ansible-2.6 -y
        - sudo apt-get update -q
      install: 
        - sudo apt-get install ansible
        - ansible --version
    - os: linux
      sudo: required
      dist: jessie
      before_install:
        - sudo add-apt-repository ppa:ansible/ansible -y
        - sudo apt-get update -q
      install: 
        - sudo apt-get install ansible
        - ansible --version

# blocklist
branches:
  except:
  - master

# safelist
branches:
  only:
  - development

# Use system installed packages inside of the Virtual environment
virtualenv:
  system_site_packages: True
