---

language: 'python'
python: '2.7'

script:
  - echo localhost > inventory
  - ansible-playbook -i inventory test.yml --syntax-check
  - ansible-playbook -i inventory test.yml --connection=local --become
  - monit -V

matrix:
  exclude:
    - os: linux
      sudo: required
      dist: 'trusty'
      before_install:
        - sudo add-apt-repository ppa:ansible/ansible-2.6 -y
        - sudo apt-get update -q
      install: 
        - sudo apt-get install ansible=2.6.1-1ppa~trusty
        - ansible --version
  include:
    - os: linux
      sudo: required
      dist: 'precise'
      install:
        - sudo add-apt-repository  ppa:ansible/ansible-2.5 -y
        - sudo apt-get update -q
        - apt-cache policy ansible
        - sudo apt-get install ansible=2.5.0-1ppa~precise
        - ansible --version
        - apt-cache policy ansible


# blocklist
branches:
  except:
  - master

# safelist
branches:
  only:
  - development

# Use system installed packages inside of the Virtual environment
virtualenv:
  system_site_packages: True
