---

- name: CONF_BASE | Ensure monit can start
  lineinfile:
    dest: "{{ monit_init_file }}"
    line: "startup=1"
    insertbefore: "START=yes"
    state: present

- name: CONF_BASE | ensure directory conf paths exist
  file:
    path: "{{ monit_path }}{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - conf-enabled
    - conf-available/templates
    - conf-available/basic
    - conf.d

- name: CONF_BASE | Update the monit configuration (/etc/monit/monitrc)
  template:
    src: "monitrc"
    dest: "{{ monit_path }}monitrc"
    mode: 0600
    owner: root
    group: root
  notify:
    - restart monit
