---

- name: install dependencies for slack alerts
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python3
    - curl

- name: CONF_BASE | Ensure monit can start
  lineinfile:
    dest: "{{ monit_init_file }}"
    line: "startup=1"
    insertbefore: "START=yes"
    state: present

- name: CONF_BASE | ensure directory conf paths exist
  file:
    path: "{{ monit_path }}{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - conf-enabled
    - conf-available/templates
    - conf-available/basic
    - conf.d

- name: CONF_BASE | copy slack alert & report files
  template:
    src: "{{ item.src }}"
    dest: "{{ monit_path }}{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - {src: 'slackAlert.sh.j2', dest: 'slackAlert.sh', mode: '0755'}
    - {src: 'slackReport.sh.j2', dest: 'slackReport.sh', mode: '0755'}
    - {src: 'monitrc.j2', dest: 'monitrc', mode: '0600'}

- name: CONF_BASE | copy conf-available service templates
  template:
    src: "{{ item }}"
    dest: "{{ monit_path }}conf-available/{{ item | basename | regex_replace('.j2','')}}"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - ../templates/conf-available/*.*

- name: CONF_BASE | copy root templates
  template:
    src: "{{ item }}"
    dest: "{{ monit_path }}templates/{{ item | basename | regex_replace('.j2','')}}"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - ../templates/rootemplates/*.*

- name: CONF_BASE | scan conf-enabled 
  shell: ls /etc/monit/conf-enabled/
  register: conf_en

- name: CONF_BASE | delete symlinks
  file:
    dest: "{{ monit_path }}conf-enabled/{{ item }}"
    state: absent
    owner: root
    group: root
  with_items:
    - "{{ conf_en.stdout_lines }}"