---

- name: create log file
  file:
    path: /etc/monit/config.log
    state: touch

- name: var time
  set_fact:
    date: "{{ '%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch) }}"

- name: lists for logfile
  lineinfile:
    path: /etc/monit/config.log
    insertafter: EOF
    state: present
    line: "[{{ date }}]  INFO  {{ item.title }} : conf={{ type_conf }} services={ {{ item.list }} }"
  with_items:
    - title: "services by user"
      list: "{{ monit_process | join(',') | default('-') }}"
    - title: "Banned Services"
      list: "{{ monit_banned | join(',') | default('-') }}"
    - title: "Available Configuration Templates"
      list: "{{ conf_available.stdout_lines | join(',') }}"
    - title: "Services Running on the SO"
      list: "{{ systemctl_services.stdout_lines | join(',') }}"
    - title: "Services by Full Templates"
      list: "{{ services_by_templates | join(',') }}"
    - title: "Services by Basic Autotemplates"
      list: "{{ services_by_autotemplates | join(',')  }}"
  when: flg == "ls"

- name: characteristics logfile
  lineinfile:
    path: /etc/monit/config.log
    insertafter: EOF
    state: present
    line: "[{{ date }}] INFO autotemp services : conf={{ type_conf }} NAME={{ item.0.item.item.name }} PID={{ item.1.stdout }} PROCMATCH={{ item.0.stdout }}"
  notify: reload_monit
  with_together:
    - "{{ lines.results }}"
    - "{{ pids.results }}"
  when: flg == "la"
