---

- include_tasks: setup-Debian.yml

- include_tasks: conf_base.yml

- include_tasks: conf_excluding.yml
  when: monit_config_mode

- include_tasks: conf_selective.yml
  when: not monit_config_mode
