---

- include_tasks: setup-Debian.yml
  when: ansible_distribution == "Debian" and ansible_distribution_version >= "8"

- include_tasks: setup-ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '12.04'

- include_tasks: conf_base.yml

- include_tasks: conf_excluding.yml
  when: monit_config_mode

- include_tasks: conf_selective.yml
  when: not monit_config_mode
